name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         ref: ${{ github.head_ref }}
         
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
          
      - name: Get previous coverage
        id: prevCoverage
        uses: notiz-dev/github-action-json-property@release
        with:
          path: '.github/badges/current_coverage.json'
          prop_path: 'coverage'    
          
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew testDebugUnitTest jacocoTestReport

        

      - name: Add coverage to PR
        id: coverage-to-pr
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          token: ${{ secrets.GIT_TOKEN }}
          min-coverage-overall: ${{steps.prevCoverage.outputs.prop}}
          min-coverage-changed-files: ${{steps.prevCoverage.outputs.prop}}
          
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: >
            ${{ github.workspace }}/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.csv
  
      - name: Create Coverage File
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "current_coverage.json"
          json: '{"coverage":${{ steps.jacoco.outputs.coverage }} }'
          dir: '.github/badges/'    
    
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update Coverage"
        
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}     
