name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
          
      - name: Get previous coverage
        id: prevCoverage
        uses: notiz-dev/github-action-json-property@release
        with:
          path: '.github/badges/current_coverage.json'
          prop_path: 'coverage'    
          
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew testDebugUnitTest jacocoTestReport

          
      - name: Log coverage percentage
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            "coverage = ${{ steps.jacoco.outputs.coverage }}"
          repo-token: ${{ secrets.GIT_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false 

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          token: ${{ secrets.GIT_TOKEN }}
          min-coverage-overall: ${{steps.prevCoverage.outputs.prop}}
          min-coverage-changed-files: ${{steps.prevCoverage.outputs.prop}}
