name: Read Json

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         ref: ${{ github.head_ref }}
      - uses: shaneapowell/github-tweak-the-json@v1
        with: 
          action: write
          filename: '.github/badges/current_coverage.json'
          field: coverage
          value: 100
    
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update Coverage"
        
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
